### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by heathmitchell** [Electroshockist/Skitscape#1]
Since the 1.13 Update, Ive noticed this with multiple texturepacks, but around half of the textures are missing (ex: oak wood planks). Its not too much of an issue per say, but Im just letting you know. I know alot of texture packs for 1.13 are incompatible with 1.13.1

**Comment by Electroshockist** [comment]
Should be fixed now. 1.13 changed some file names, causing some missing textures.
Let me know if I missed any.

Thanks for your support.
